# irc server name
host: irc.freenode.net
# irc server port
port: 6667
# nick name of the bot
nickname: zircbot
# password of the nick name
password: ''
# 0MQ socket connection: bind|connect
method: connect
# 0MQ Endpoint
endpoint: tcp://localhost:7777
# association between applications and irc channels
trello:
  <BOARD_SHORT_ID>: ['#mychan']
  <BOARD_SHORT_ID_2>: ['#mychan2']
sensu:
  <SENSU_DC_NAME>: ['#mychan-admin']
gerrit:
  <project regexp>: ['mychan3']
