# irc server name
host: irc.freenode.net
# irc server port
port: 6667
# irc chans to forward the message to
channels: ['#mychan']
# nick name of the bot
nickname: zircbot
# password of the nick name
password: ''
# 0MQ socket connection: bind|connect
method: connect
# 0MQ Endpoint
endpoint: tcp://localhost:7777
